image: ruby:2.4.5-stretch

services:
  - postgres:11.1-alpine

variables:
  POSTGRES_DB: vision_test
  POSTGRES_USER: root
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  DATABASE_URL: postgresql://root@postgres/vision_test
  BUNDLE_PATH: /cache/vision/gems

stages:
  - test

before_script:
  - mkdir -p /cache/debs
  - ln -sf /cache/debs /var/cache/apt
  - apt-get update
  - curl -sL https://deb.nodesource.com/setup_11.x | bash -
  - apt-get -y install nodejs
  - gem install bundler --version 1.17.3
  - bundle install --retry 10 --quiet --deployment --path=$BUNDLE_PATH
  - npm install -g bower
  - mkdir -p /cache/bower_components
  - rm -rf vendor/assets/bower_components
  - cp -r /cache/bower_components vendor/assets/bower_components
  - rm -rf vendor/assets/bower_components/bower_components
  - bower install --allow-root
  - rm -rf /cache/bower_components
  - cp -r vendor/assets/bower_components /cache/bower_components

format:
  stage: test
  script:
    - bundle exec rubocop

rspec:
  stage: test
  script:
    - bundle exec rake db:migrate > /dev/null
    - bundle exec rspec --tty
