AllCops:
  Exclude:
    - 'Guardfile'
    - 'db/schema.rb'
    - 'features/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    # baby step
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'
    - 'app/assets/**/*'
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - 'app/models/**/*'
    - 'app/views/**/*'

# we are not ready for its power
Style/MethodCallWithArgsParentheses:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120

# special configuration for vision
Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - ir
    - cr

Naming/PredicateName:
  NamePrefix:
    - is_
  NamePrefixBlacklist:
    - is_

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

