version: "3.9"
services:
  db:
    image: postgres:12.8
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"

  solr:
    image: solr:5.5.5-alpine
    volumes:
      - solr_data:/var/solr
      - solr_init:/docker-entrypoint-initdb.d/
      - solr_core_data:/opt/solr/server/solr/mycores
    restart: always
    ports:
      - "8983:8983"

  web:
    build: .
    depends_on:
      - db
      - solr
    env_file:
    - .env.docker
    volumes:
      - app_data:/app
    restart: always
    ports:
      - "3000:3000"

volumes:
  db_data: {}
  solr_data: {}
  solr_core_data: {}
  solr_init: {}
  app_data: {}
  search_data: {}