version: "3.9"
services:
  db:
    image: postgres:12.8
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    env_file:
    - .env.docker
    volumes:
      - app_data:/app
    restart: always
    ports:
      - "3000:3000"

volumes:
  db_data: {}
  app_data: {}
  search_data: {}