defaults: &defaults
  google:
    api_key: "772021837446-vnbketkbvppb2o38lrnrjtdt4v2cfi2g.apps.googleusercontent.com"
    api_secret: "dxIshXuB0zqC2enaPZZx4ooL"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  google:
    api_key: "772021837446-rmg7jpjr3lk3uruq3k7i466nidj707ln.apps.googleusercontent.com"
    api_secret: "wOzkCxmldUG8M2S9xQ6WhPiY"