defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  timeout: 5000
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *defaults
  database: vision_dev

test:
  <<: *defaults
  database: vision_test
