staging:
  disabled: true
development:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST") { localhost } %>
    port: <%= ENV.fetch("SOLR_PORT") { 8983 } %>
    log_level: INFO
    path: /solr/development
test:
  solr:
    hostname: <%= ENV.fetch("SOLR_HOST") { localhost } %>
    port: <%= ENV.fetch("SOLR_PORT") { 8983 } %>
    log_level: WARNING
    path: /solr/test