menubar: false
plugins: ['textcolor link image tabfocus ']
toolbar: 'undo redo | styleselect | bold italic| alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | forecolor' 
theme: "modern" 
browser_spellcheck: true
