defaults: &defaults
  

development:
  <<: *defaults

  something: "tes"

test:
  <<: *defaults
  something: "tes"

staging:
  <<: *defaults
  something: "tes"

production:
  <<: *defaults
  something: "tes2"
