name: CodeCoverage

on:
  pull_request:
    branches: [ main ]

env:
  CODE_COVERAGE: ${{ secrets.X_CODE_COVERAGE }}

jobs:
  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
      with:
        ruby-version: 2.7.3
    
    - name: Install dependencies
      run: bundle install

    # - name: Code Coverage
    #   run: app_code_coverage $CODE_COVERAGE