name: Deploy

on:
  pull_request:
    branches: [ development ]

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.X_HEROKU_DEPLOY_KEY}}
        heroku_app_name: "vision-demo-app"
        heroku_email: "rori.development@gmail.com"
        usedocker: true
        stack: "container"
        healthcheck: "https://vision-demo-app.herokuapp.com/signin"
        rollbackonhealthcheckfailed: true
      env:
        HD_INCIDENT_LEVEL_GUIDELINE: "https://drive.google.com/file/d/1i3SuJ85OmvIrzqzpYTzIPQzu3gAgS2no/preview"
        HD_LANG: "en_US.UTF-8"
        HD_RAILS_ENV: "staging"
        HD_TZ: "Asia/Jakarta"
        HD_VALID_EMAIL: "midtrans.com,veritrans.co.id,associate.midtrans.com,spots.co.id,go-jek.com,gmail.com"
        HD_VISION_EMAIL: "visiongojek@gmail.com"
    
