name: UnitTest

on:
  pull_request:
    branches: [ development ]

env:
  CODE_COVERAGE: ${{ secrets.X_CODE_COVERAGE }}

jobs:
  unit_test:
    name: Run Unit Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      mailcatcher:
        image: tophfr/mailcatcher
        ports:
          - 1025:1025

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
      with:
        ruby-version: 2.7.3
    
    - name: Setup node 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    
    - name: Install dependencies
      run: |
        bundle install
        npm install
    - name: Rspec (Unit Test)
      run: |-
        mv config/database.test.yml config/database.yml
        RAILS_ENV=test bundle exec rake db:create
        RAILS_ENV=test bundle exec rake db:migrate
        RAILS_ENV=test bundle exec rspec --tty
      env:
        APPROVER_EMAIL: approver@midtrans.com
        ENTITY_SOURCES: midtrans,spots,gojek
        JIRA_URL: https://veritrans.atlassian.net/
        DB_PASSWORD: postgres
        SLACK_IR_CHANNEL: midtrans-test,spots-test,gojek-test,anything
        SLACK_CR_CHANNEL: midtrans-test,spots-test,gojek-test,anything
        VALID_EMAIL: midtrans.com,veritrans.co.id,associate.midtrans.com,spots.co.id,go-jek.com,gmail.com
